[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[context.production]
  environment = { BUILD_IMAGE = "noble" }

[context.deploy-preview]
  environment = { BUILD_IMAGE = "noble" }

[context.branch-deploy]
  environment = { BUILD_IMAGE = "noble" }
