// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://gbymaocwwyekwzxldayk.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdieW1hb2N3d3lla3d6eGxkYXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxNjA2OTMsImV4cCI6MjA0ODczNjY5M30.TCg2amXljuaU-C0KaDI9Qt1oaS5f83M8jw00x1M8_CU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);